@extends('layouts.app')
@section('content')
<div class="page-heading-row"><div><h1>Financial Reports</h1><p>Rekap pemasukan dan pengeluaran berdasarkan periode dan kategori.</p></div><div class="hero-actions"><button class="outline-button" onclick="window.print()">Download PDF</button><button class="gold-button" onclick="downloadTableCsv('reportTable','odeon-report.csv')">Export to Excel</button></div></div>
<form class="filter-panel report-filter" method="GET"><select name="month">@foreach(range(1,12) as $m)<option value="{{ $m }}" @selected($m===$month)>{{ \Illuminate\Support\Carbon::create()->month($m)->format('F') }}</option>@endforeach</select><select name="year">@foreach(range(now()->year-2,now()->year+1) as $y)<option @selected($y===$year)>{{ $y }}</option>@endforeach</select><select name="type"><option value="">All Types</option><option value="income" @selected($type==='income')>Pemasukan</option><option value="expense" @selected($type==='expense')>Pengeluaran</option></select><button class="outline-button" type="submit">Terapkan</button></form>
<div class="metric-grid report-metrics"><section class="metric-card"><div class="metric-label">Total Revenue</div><div class="metric-value">{{ rupiah($income) }}</div></section><section class="metric-card"><div class="metric-label">Total Expenses</div><div class="metric-value">{{ rupiah($expense) }}</div></section><section class="metric-card net"><div class="metric-label">Net Profit Margin</div><div class="metric-value">{{ number_format($income ? ($net/$income)*100 : 0,1,',','.') }}%</div><div class="metric-meta">Net: {{ rupiah($net) }}</div></section></div>
<div class="dashboard-grid report-grid"><section class="panel chart-panel"><div class="panel-heading"><h2>Expense Distribution</h2><span>Per kategori (rekapan)</span></div><div class="donut-wrap">
@php($offset=0)
@php($segments=[])
@foreach($distribution as $item)
    @php($next=$offset+$item->percentage)
    @php($segments[] = ($loop->index % 4 === 0 ? '#a24945' : ($loop->index % 4 === 1 ? '#7e6210' : ($loop->index % 4 === 2 ? '#d3c7b3' : '#5e2b2d'))) . ' ' . $offset . '% ' . $next . '%')
    @php($offset=$next)
@endforeach
<div class="donut" style="background:conic-gradient({{ implode(',', $segments) ?: '#eee5d8 0 100%' }})"><div><small>Total</small><b>{{ rupiah($expense,true) }}</b></div></div><div class="distribution-list">@foreach($distribution as $item)<div><span><i class="dot {{ $loop->index%2 ? 'red' : 'gold' }}"></i>{{ $item->category_name }}</span><b>{{ $item->percentage }}%</b></div>@endforeach @if($distribution->isEmpty())<div class="empty-state">Belum ada pengeluaran untuk periode ini.</div>@endif</div></div></section>
<section class="panel"><div class="panel-heading"><h2>Recent Entries</h2><a href="{{ route('transactions.index') }}">View Full Ledger →</a></div><div class="table-scroll"><table id="reportTable"><thead><tr><th>Date</th><th>Description</th><th>Category</th><th>Place</th><th>Reference</th><th>Amount</th></tr></thead><tbody>@foreach($transactions as $t)<tr><td>{{ $t->transaction_date->format('d M Y') }}</td><td>{{ $t->description }}</td><td><span class="tag">{{ $t->category?->name }}</span></td><td>{{ $t->tourismPlace?->name ?? '-' }}</td><td>{{ $t->package_name ?? '-' }}</td><td class="{{ $t->type==='income'?'amount-income':'amount-expense' }}">{{ $t->type==='income'?'+':'-' }}{{ rupiah($t->amount) }}</td></tr>@endforeach</tbody></table></div></section></div>
@endsection
