@extends('layouts.app')
@section('content')
<div class="page-heading-row"><div><h1>Master Data</h1><p>Kelola isi dropdown kategori, tempat wisata, dan sumber pendapatan.</p></div></div>
<div class="master-grid">
<section class="panel master-card"><div class="panel-heading"><h2>Tempat Wisata</h2></div><form class="inline-master-form" method="POST" action="{{ route('masters.places.store') }}">@csrf<input name="name" placeholder="Tempat wisata baru" required><input name="description" placeholder="Keterangan"><button class="gold-button" type="submit">Tambah</button></form><div class="master-list">@foreach($places as $place)<div class="master-row"><form method="POST" action="{{ route('masters.places.update',$place) }}" class="master-edit-form">@csrf @method('PUT')<input name="name" value="{{ $place->name }}"><input name="description" value="{{ $place->description }}"><label><input type="checkbox" name="is_active" value="1" @checked($place->is_active)> Aktif</label><button class="text-button" type="submit">Simpan</button></form></div>@endforeach</div></section>
<section class="panel master-card"><div class="panel-heading"><h2>Kategori</h2></div><form class="inline-master-form" method="POST" action="{{ route('masters.categories.store') }}">@csrf<input name="name" placeholder="Kategori baru" required><select name="type"><option value="income">Income</option><option value="expense">Expense</option><option value="both">Both</option></select><button class="gold-button" type="submit">Tambah</button></form><div class="master-list">@foreach($categories as $category)<div class="master-row"><form method="POST" action="{{ route('masters.categories.update',$category) }}" class="master-edit-form">@csrf @method('PUT')<input name="name" value="{{ $category->name }}"><select name="type"><option value="income" @selected($category->type==='income')>Income</option><option value="expense" @selected($category->type==='expense')>Expense</option><option value="both" @selected($category->type==='both')>Both</option></select><label><input type="checkbox" name="is_active" value="1" @checked($category->is_active)> Aktif</label><button class="text-button" type="submit">Simpan</button></form></div>@endforeach</div></section>
<section class="panel master-card"><div class="panel-heading"><h2>Sumber Pendapatan</h2></div><form class="inline-master-form" method="POST" action="{{ route('masters.sources.store') }}">@csrf<input name="name" placeholder="Sumber pendapatan baru" required><button class="gold-button" type="submit">Tambah</button></form><div class="master-list">@foreach($sources as $source)<div class="master-row"><div><b>{{ $source->name }}</b><small>Dropdown income</small></div></div>@endforeach</div></section>
</div>
@endsection
